[package]
name = "explore"
version = "0.1.0"
authors = ["S. <smonfourny@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "0.8.1"
specs = "0.16.1"
specs-derive = "0.4.1"